#
# Module manifest for module 'SxBuildHelpers'
#
# Generated by: Alexis Coles
#
# Generated on: 18/12/2015
#

@{
	RootModule = 'HttpSys.psm1'
	ModuleVersion = '2.8.16'
	GUID = 'dc6db6aa-9f02-4f9c-bf58-8c15ec06588c'
	Author = 'Alexis Coles'
	CompanyName = 'Spreadex'
	Copyright = '(c) Spreadex 2018 . All rights reserved.'
	Description = 'Module designed to expose netsh http functionality in object form'
	RequiredModules = @(
			@{'ModuleName' = 'SxDevops'; 'ModuleVersion' = '2.14.1'}
		)
	FunctionsToExport = '*'
	CmdletsToExport = @(
		'Get-UrlAcl'
	)
	VariablesToExport = '*'
	AliasesToExport = '*'
    
	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{

		PSData = @{

			# ReleaseNotes of this module
			ReleaseNotes = @(				
				'Version 1.0.0', "Added Get-UrlAcl cmdlet"
			)

			# External dependent modules of this module
			# ExternalModuleDependencies = ''

		} # End of PSData hashtable
    
	 } # End of PrivateData hashtable
}

